Cloudcasav3.0.0
digitalocean/marketplace-kubernetes pull request #323
Opened 2022-02-17 08:45 UTC by nitishdsharma

Updates
-----------------------------------------------------------
- Kubernetes security posture management
- Selecting Kubernetes resources for restore by type
- Cross-cluster restore improvements
- Agent auto-updates
- Azure object store support for BYO Storage

2022-02-17 21:49 UTC, paulanunda requested changes
I'm getting a crashloopbackoff in the pod:

```
marketplace-kubernetes git:pr/323 ❯ k logs cloudcasa-kubeagent-manager-6fc5c55c5c-xwqqv
2022-02-17T21:48:21.395Z	INFO	agentlog/agentlog.go:23	Initialized logger
2022-02-17T21:48:21.395Z	INFO	kubeagentmanager/main.go:579	Initialized the logger
2022-02-17T21:48:21.395Z	ERROR	kubeagentmanager/main.go:585	Exiting...	{"error": "could not find cluster ID"}
main.main
	/tmp/build/80754af9/cloudcasa-git/kubeclusters/kubeagentmanager/main.go:585
runtime.main
	/usr/local/go/src/runtime/proc.go:255
```

2022-02-22 13:21 UTC, nitishdsharma commented
@paulanunda There is a way to provide the clusterID. Please refer the **Getting started after deploying CloudCasa** section on https://marketplace.digitalocean.com/apps/cloudcasa page.

2022-03-08 10:53 UTC, sabir-catalogic commented
@paulanunda can you please review this PR.

2022-03-11 21:59 UTC, paulanunda approved these changes

2022-03-11 21:59 UTC, merged