Add instructions to Easegress
digitalocean/marketplace-kubernetes pull request #478
Opened 2023-09-19 08:06 UTC by LokiWager

## BACKGROUND
* Add information about the background and reason for the change.
https://github.com/digitalocean/marketplace-kubernetes/pull/477
Add instructions to Easegress.

-----------------------------------------------------------------------

## Changes
* List the changes that you made

- add `stacks/easegress/README.md`
- add `stacks/easegress/imgs/architecture.png`
- add `stacks/easegress/values.yml`

-----------------------------------------------------------------------

## Checklist
- [x] review the [contributing doc](https://github.com/digitalocean/marketplace-kubernetes/blob/master/CONTRIBUTING.md) with steps for both adding or updating your application (if applicable)
------------------------------------------------------------------------

Reviewer: @marketplace-eng

2023-09-21 22:32 UTC, msannan2 requested changes

2023-09-21 22:32 UTC, msannan2 commented on stacks/easegress/README.md
> +http://10.108.162.15:30780
Have this been tested DOKS? Is the service accessible with the NODE_IP or does it require a LoadBalancer as well?

2023-09-27 16:15 UTC, bikram20 approved these changes
Only content changes. No engg review needed.

2023-09-28 04:06 UTC, LokiWager commented
I’m sorry, I didn’t receive the github notification. I will make the necessary changes as soon as possible. @bikram20 thank you.

2023-09-28 09:07 UTC, msannan2 approved these changes
LGTM

2023-10-13 16:48 UTC, merged