Adding the first version of Atm0s Media Server Stack to the marketplace
digitalocean/marketplace-kubernetes pull request #505
Opened 2024-01-22 04:18 UTC by luongngocminh

## BACKGROUND
* First time publishing the one-click server stack.
-----------------------------------------------------------------------

## Changes
- Scripts for deploy, uninstall and upgrade
- Readme

-----------------------------------------------------------------------

## Checklist
- [x] review the [contributing doc](https://github.com/digitalocean/marketplace-kubernetes/blob/master/CONTRIBUTING.md) with steps for both adding or updating your application (if applicable)
------------------------------------------------------------------------

Reviewer: @marketplace-eng

2024-01-24 15:23 UTC, msannan2 requested changes

2024-01-24 15:23 UTC, msannan2 commented on stacks/atm0s-media-stack/deploy.sh
> +CHART_VERSION="0.1.2"
Helm chart version 0.1.2 is not available. Only version I see is 0.1.0
![Screenshot 2024-01-24 at 8 22 58 PM](https://github.com/digitalocean/marketplace-kubernetes/assets/36917391/18c04e23-65bb-4cbf-bfe6-232aad1d1959)

2024-01-28 02:26 UTC, luongngocminh commented
@msannan2 can you re-review this back please

2024-01-28 17:12 UTC, msannan2 approved these changes
LGTM!

2024-01-28 17:12 UTC, merged